### ISSUE TITLE
GCAM Fails on Build with Boost 1.64, but works with 1.62 --- Warning

### ISSUE THREAD

**Issue by michaeljaywalsh** [JGCRI/gcam-core#21]
I tried recompiling GCAM Today (Mint18.2) with a new version of Boost (1.64). Make failed on the two steps listed below. Compiling worked when Boost was rolled back to 1.62 
 
`g++ -O2 -ggdb -DNDEBUG  -MMD -std=c++11 -Wno-deprecated -I/gcam-core/libs/boost-lib -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux -I/gcam-core/libs/tbb/tbb2017_20170604oss/include -I/gcam-core/libs/boost-lib/boost/numeric/ -I../../climate/source/hector/headers -I/gcam-core/libs/xercesc/include -I../../.. -I/home/michael/include   -DJARS_LIB="\"/gcam-core/libs/jars/*\"" -DGCAM_PARALLEL_ENABLED=1 -DUSE_LAPACK=1 -DNOCLEARNULL=0 -DNOCLEARRESTORE=0 -DUSE_HECTOR=1 -fopenmp -I/opt/intel/mkl/include  -c -o solution_info_filter_factory.o solution_info_filter_factory.cpp
In file included from /gcam-core/libs/boost-lib/boost/numeric/ublas/vector.hpp:21:0,
                 from /gcam-core/libs/boost-lib/boost/numeric/ublas/matrix.hpp:18,
                 from ../../../solution/util/include/solver_library.h:51,
                 from solution_info.cpp:47:
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^
In file included from ../../../solution/util/include/solver_library.h:51:0,
                 from solution_info.cpp:47:
/gcam-core/libs/boost-lib/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
/gcam-core/libs/boost-lib/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, N);
                  ^
`

and with: 

`g++ -O2 -ggdb -DNDEBUG  -MMD -std=c++11 -Wno-deprecated -I/gcam-core/libs/boost-lib -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux -I/gcam-core/libs/tbb/tbb2017_20170604oss/include -I/gcam-core/libs/boost-lib/boost/numeric/ -I../../climate/source/hector/headers -I/gcam-core/libs/xercesc/include -I../.. -I/home/michael/include   -DJARS_LIB="\"/gcam-core/libs/jars/*\"" -DGCAM_PARALLEL_ENABLED=1 -DUSE_LAPACK=1 -DNOCLEARNULL=0 -DNOCLEARRESTORE=0 -DUSE_HECTOR=1 -fopenmp -I/opt/intel/mkl/include  -c -o subresource.o subresource.cpp
In file included from /gcam-core/libs/boost-lib/boost/numeric/ublas/vector.hpp:21:0,
                 from ../../solution/util/include/ublas-helpers.hpp:37,
                 from marketplace.cpp:61:
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
/gcam-core/libs/boost-lib/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^
In file included from ../../solution/util/include/ublas-helpers.hpp:38:0,
                 from marketplace.cpp:61:
/gcam-core/libs/boost-lib/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
/gcam-core/libs/boost-lib/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, N);
                  ^
`

**Comment by rplzzz** [comment]
This appears to be a known issue with Boost 1.64.0:
https://github.com/dealii/dealii/issues/4302

The conversation thread there is a little confusing, but it looks like the problem is fixed in a later version (https://github.com/dealii/dealii/issues/4302#issuecomment-296771294 and  https://github.com/dealii/dealii/issues/4302#issuecomment-296832915), so the solution might just be to blacklist boost v.1.64.0.  Alternatively, we could put in a workaround to deal with the special case of that particular version of boost.
